yamada-ui/yamada-components

- data/categories.ts
- data/components.ts
- pages/category/[category].page.tsx
- utils/assetion.ts
- utils/contentlayer.ts
Closes #11 
コンポーネントのディレクトリ構造からカテゴリページのパスを生成
`data/categories.ts`に直書きしてある`CATEGORIES`を参照してページのパスを生成
`contents`配下のパスをパースしてページのパスを生成
> feat: make category directory by components directory

- components/data-display/categories-display.tsx
- components/data-display/categories-group-display.tsx
- contents/application-ui/headers/header-2/index.ja.tsx
- contents/application-ui/headers/header-2/index.tsx
- contents/application-ui/headers/header/index.ja.tsx
- i18n/ui.en.json
- i18n/ui.ja.json
- utils/component.ts
- utils/next.ts
Closes #30
Added `i18n` and `index.ja.tsx` support.
`i18n` did not work properly in component pages.
Make `i18n` work and allow multi-language components.
No
Should we have one `object` that would have all metadata for all languages? If so, should we prioritise the `metadata` if it already exists in `index.ja.tsx`?
> Added `i18n`

- components/data-display/category-card.tsx
- components/data-display/category-group.tsx
- components/data-display/category.tsx
- i18n/ui.en.json
- i18n/ui.ja.json
- pages/index.page.tsx
Closes #96
I have translated component and category count to Japanese.
In both languages, it said "... components/categories".
Now says "...個のコンポーネント/カテゴリー"
No
> Translated category and component counts

- contents/page-sections/error-pages/404-page/metadata.json
- contents/page-sections/error-pages/500-page/index.tsx
- contents/page-sections/error-pages/with-image/metadata.json
Closes #221
Fixed the height of error pages examples and also made them centre.
Height was not fit properly and it was not centred vertically.
Fixes the background color height and centre examples.
No
> fix(error-pages): fixed the height of error-pages examples

- pages/search/index.page.tsx
Closes #223
This PR makes the page display 404 when search result is not found.
Showed empty result.
Shows 404.
No
I have not fixed the NextJS error when switching locale, and this is not allowing me to add a check to see if label query is there.
> feat(search): add 404 display when search result is not found

- contents/navigation/navbars/navbar-with-segmentedcontrol/index.tsx
- contents/navigation/navbars/navbar-with-segmentedcontrol/metadata.json
> feat: add `NavbarWithSegmentedcontrol`

- contents/data-display/banners/announcement/index.tsx
- contents/data-display/banners/announcement/metadata.json
Closes #252 
add `announcement` component as `Banners` category.
No
None
> add `announcement` component as `Banners` category.

- components/data-display/component-card.tsx
Closes #262
This fixes `z-index` of `component card` which made overlays in component preview overlap.
No
> fix(component-card): fixed `z-index` of component-card

- utils/component.ts
Closes #276
Fixed `theme` and `config` not working on Windows.
`path.join` joins path with `\\`.
The paths are now joined with `/`.
No
> fix(path): fixed `theme` and `config` path having `\\` instead of `/`

- contents/typography/texts/on-scroll/index.tsx
- contents/typography/texts/on-scroll/metadata.json
Closes #150
This adds a `text` component example that reveal on scroll.
No
This may be performance heavy, and could potentially be improved.
> feat(texts): added reveal on scroll `text` example

- contents/layouts/headers/with-tabs/index.tsx
Closes #274
Removed `useBreakpointValue`.
We were using `useBreakpointValue`.
I have changed it to implement changing the orientation of tabs using alternative method.
No
> refactor(header): removed `useBreakpointValue`

- contents/forms/button-group/basic-button-group/metadata.json
fix format for Basic Button Group in contents/forms/button-group/basic-button-group/metadata.json
Closes # Github issue #321
> fix: format for Basic Button Group

- contents/data-display/comments/comment/index.tsx
- contents/data-display/comments/with-html-content/index.tsx
Closes #317
I have replaced `_container` with Yamada UI breakpoints.
The example was using `_container` to make it responsive.
I have changed to use Yamada UI breakpoints such as `sm` to be responsive.
No
> refactor(comments): replaced `comments` example to be responsive using `breakpoints`

- contents/page-sections/error-pages/with-image/index.tsx
Closes #316
I have replaced `_container` with Yamada UI breakpoints.
The example was using `_container` to make it responsive.
I have changed to use Yamada UI breakpoints such as `{{sm: }}` to be responsive.
No
> refactor(error-pages): replaced `_container` prop with yamada-ui breakpoint

- @types/component.d.ts
- utils/component.ts
Closes #492  
Added functionality to hide components and categories when ignore is specified in the metadata option.
> Add `ignore` process

- contents/navigation/paginations/simple-button/index.tsx
Closes #516 
Fixes the issue of nested buttons in the pagination component by refactoring the button rendering logic. The `controlPrevProps` and `controlNextProps` were updated to remove the nesting and ensure styling consistency.
The `Pagination` component currently renders buttons with nested button elements, which is semantically incorrect and causes issues with the UI.
The pagination buttons now render with text only (e.g., "Prev" and "Next"), and all styling is applied directly to the buttons themselves. This removes the nested button structure and ensures that the buttons are styled correctly while maintaining the same appearance.
No
None
> fix(pagination): resolve nested button issue in pagination component

- utils/component.ts
- utils/next.ts
Closes #531
I have fixed the hidden components that were appearing in list.
It was not checking whether the component tree has items or not.
It will filter out the item in componentTree that does not have an item.
No
I am still unsure of the best way to make the category group page 404.
(e.g. /data-display). If you have a good idea to this, please let me know, otherwise we can fix it in another PR.
> Fixed hidden components appearing in list

- components/data-display/component-preview.tsx
Closes #536
I have fixed the issue with demo overflowing the preview.
The demo content overflowed vertically due to `h="full"`.
I ave removed height from the default container props.
Possible
I have checked the other components, but please also double check if the examples are not breaking.
> refactor(component-preview): removed default `height` prop from `containerProps`

- contents/navigation/navbars/metadata.json
- contents/navigation/navbars/navbar-with-search/index.tsx
- contents/navigation/navbars/navbar-with-search/metadata.json
Closes #527 
This PR introduces a new demo, `Navbar with Search box` for the Yamada component, specifically the `Navigation` category, `Navbar` component
Currently, the Yamada components lack a demo for a `navbar with search` in the `Navigation` category.
Add `navbar with search` component to `Navigation` categories
No
I am still new to Yamada UI, welcome any suggestions or feedback to improve the component or code quality. Your insights would be greatly appreciated! 🙌 ❤️
> feat(navbars): add navbar with search component

- scripts/search-content.ts
Closes #539
I have fixed the issue with `search-content` script and added try catch.
It was also reading the `contents/metadata.json` which only contain order array.
Added an ignore to the path and added try catch.
No
N/A
> fix(search-content): fixed `search-content` script failing
