yamada-ui/yamada-components

- components/component-preview/index.tsx
- components/layouts/category-card.tsx
- pages/category/[category].page.tsx
- pages/component/[component].page.tsx
- pages/index.page.tsx
Closes #2 
- Add `Card` component
- fix eslint error
> Add `Card` component

- components/layouts/category-card.tsx
- pages/index.page.tsx
Closes #8
Improve `Card` styles
Very simple `Card` and also uses `Grid`
Improved styles of `Card` and use `Wrap`
No
> Improve `Card` styles

- layouts/component-layout.tsx
- pages/application-ui/[[...slug]].page.tsx
- pages/blog-ui/[[...slug]].page.tsx
- pages/page-sections/[[...slug]].page.tsx
Closes # 
> Add a brief description
> Please describe the current behavior that you are modifying
> Please describe the behavior or changes this PR adds
> feat: add `ComponentLayout`

- contents/blog-ui/stats/progress-card/index.ja.tsx
- contents/blog-ui/stats/progress-card/index.tsx
- pages/blog-ui/[[...slug]].page.tsx
- pages/page-sections/[[...slug]].page.tsx
Closes #18 
Add `Stats` component
> Add `Stats` Component

- contents/application-ui/inputs/password-input/index.ja.tsx
Closes #22 
Add `PasswordInput` ja version
> feat(inputs): add password-input ja version

- @types/resct.ts
- components/layouts/component-preview.tsx
- components/layouts/detail-component.tsx
- contents/application-ui/buttons/copybutton/index.ja.tsx
- contents/application-ui/buttons/copybutton/index.tsx
- contents/application-ui/footers/footercenterd/index.tsx
- contents/application-ui/headers/header/index.ja.tsx
- contents/application-ui/headers/header/index.tsx
- contents/application-ui/inputs/password-input/index.ja.tsx
- contents/application-ui/inputs/password-input/index.tsx
- contents/blog-ui/dropzone/with-image-preview/index.ja.tsx
- contents/blog-ui/dropzone/with-image-preview/index.tsx
- pnpm-lock.yaml
Closes # 
以下のように`CFC`の型を使って`metadata`を渡せるようにした。
```tsx
import type { UsageTheme } from "@yamada-ui/react"
import { Box, HStack, Heading, extendTheme } from "@yamada-ui/react"
import type { CFC } from "react"
import { LinkItem } from "./link-item"
import type { ComponentMetadata } from "types"
const links = [
{ link: "#", label: "Home" },
{ link: "#", label: "Contact" },
{ link: "#", label: "Privacy" },
{ link: "#", label: "Teams" },
{ link: "#", label: "About" },
]
const Header: CFC = ({ metadata }) => {
console.log(metadata)
return (
<HStack as="header" justify="space-between">
<Box>
<Heading color="banner">Icon</Heading>
</Box>
<HStack>
{links.map((item, index) => (
<LinkItem key={index} {...{ item }} />
))}
</HStack>
</HStack>
)
}
export const theme: UsageTheme = extendTheme({ …
```
> コンポーネント内でCFCの型でmetadataを渡せるようにする

- contents/blog-ui/dropzone/with-image-preview/config.ts
- contents/blog-ui/dropzone/with-image-preview/index.tsx
- contents/blog-ui/stats/progress-card/index.tsx
- pages/blog-ui/[[...slug]].page.tsx
- pages/page-sections/[[...slug]].page.tsx
Closes # 
@hirotomoyamada 
`blog-ui`のコンポーネントが404になっていたので、`[[..slug]].page.tsx`内の記述を修正しました。
`metadata`と`config`もコンポーネント内に書かれてるものは消してます。
マージお願いします。
> Please describe the current behavior that you are modifying
> Please describe the behavior or changes this PR adds
> `blog-ui`のコンテンツが表示されなかったので修正

- contents/application-ui/footers/footer-centerd/metadata.json
- contents/application-ui/footers/footer-links/index.tsx
- contents/application-ui/footers/footer-links/metadata.json
- contents/application-ui/footers/footer-simple/index.tsx
- contents/application-ui/footers/footer-simple/metadata.json
- contents/application-ui/footers/footer-social-icons/index.tsx
- contents/application-ui/footers/footer-social-icons/metadata.json
Closes #69
Added 4 components to `Footers`
No
Brand icons in `lucide-react` is deprecated.
> Added `Footers`

- .github/workflows/observe-pull-requests.yml
- package.json
- pnpm-lock.yaml
- scripts/observe-pull-requests.ts
- scripts/utils.ts
> Add GitHub Action for PRs

- contents/blog-ui/comments/comment/index.tsx
- contents/blog-ui/comments/comment/metadata.json
- contents/blog-ui/comments/metadata.json
- contents/blog-ui/comments/with-html-content/index.tsx
- contents/blog-ui/comments/with-html-content/metadata.json
Closes #92 
Adds `Comments`.
This PR adds `Comments`.
No
It currently have my profile image and username as an example, but I am happy to change it to someone else if requested.
> Added `Comments`

- contents/application-ui/grids/asymmetrical-columns/index.tsx
- contents/application-ui/grids/asymmetrical-columns/metadata.json
- contents/application-ui/grids/leading-item/index.tsx
- contents/application-ui/grids/leading-item/metadata.json
- contents/application-ui/grids/metadata.json
Closes #72
Added `Grids`.
This PR adds `Grids`.
No
> Added `Grids`

- components/data-display/category-card.tsx
- components/data-display/category-group.tsx
- components/data-display/category.tsx
- contexts/i18n-context.tsx
- i18n/ui.en.json
- i18n/ui.ja.json
- pages/index.page.tsx
Enhanced translation functionality with patterns.
No
> Enhanced translation functionality with patterns

- @types/next.d.ts
- pages/_app.page.tsx
- pages/application-ui/[[...slug]].page.tsx
- pages/blog-ui/[[...slug]].page.tsx
- pages/page-sections/[[...slug]].page.tsx
- plop/addition/config.ts.hbs
- plop/category-group/metadata.json.hbs
- plop/category/metadata.json.hbs
- plop/component/index.tsx.hbs
- plop/component/metadata.json.hbs
- plop/optional/config.ts.hbs
- plop/optional/theme.ts.hbs
- plop/pages/[[...slug]].page.tsx.hbs
- plopfile.mjs
- utils/next.ts
- utils/ui.ts
Update templates and refactor code.
No
> Update templates and refactor code

- contents/page-sections/error-pages/404-page/index.tsx
- contents/page-sections/error-pages/404-page/metadata.json
- contents/page-sections/error-pages/500-page/index.tsx
- contents/page-sections/error-pages/500-page/metadata.json
- contents/page-sections/error-pages/metadata.json
- contents/page-sections/error-pages/with-image/index.tsx
- contents/page-sections/error-pages/with-image/metadata.json
Closes #88
Added `Error pages`.
This PR adds `Error pages`.
No
> Added `Error pages`

- contents/application-ui/footers/footer-centerd/index.tsx
- contents/application-ui/footers/footer-links/index.tsx
- contents/application-ui/footers/footer-simple/index.tsx
- contents/application-ui/footers/footer-social-icons/index.tsx
- contents/application-ui/footers/metadata.json
Closes #119
This PR makes `Footer` components responsive even with resize.
Uses screen size to change styles.
Now uses `@container`.
No
> Make `Footer` responsive with resize.

- contents/page-sections/error-pages/with-image/index.tsx
- contents/page-sections/error-pages/with-image/metadata.json
Closes #123 
This PR makes `Error pages` more responsive using `@container`.
No
> Made `Error pages` responsive

- contents/application-ui/grids/asymmetrical-columns/index.tsx
- contents/application-ui/grids/asymmetrical-columns/metadata.json
- contents/application-ui/grids/leading-item/index.tsx
- contents/application-ui/grids/leading-item/metadata.json
- contents/application-ui/grids/metadata.json
Closes #121
This PR makes `Grid` components responsive even with resize.
Uses screen size to change styles.
Now uses `@container`.
No
> Make `Grids` responsive

- .github/pull_request_template.md
Related yamada-ui/yamada-ui#1674
Updated pull request template formatting.
No
> Updated pull request template formatting

- CONTRIBUTING.ja.md
- CONTRIBUTING.md
Closes #114
Updated contributing guidelines and commands.
No
> Updated contributing guidelines and commands

- components/forms/search.tsx
- components/layouts/header.tsx
- constant/index.ts
- constant/path.ts
- contexts/i18n-context.tsx
- i18n/content.en.json
- i18n/content.ja.json
- scripts/search-content.ts
- utils/path.ts
> Fixed search content

- scripts/observe-pull-requests.ts
Updated DISCORD_USER_MAP entries.
No
> Updated DISCORD_USER_MAP entries

- scripts/observe-pull-requests.ts
Updated OMIT_GITHUB_IDS list.
No
> Updated OMIT_GITHUB_IDS list

- contents/typography/headings/full-gradient-heading/index.tsx
- contents/typography/headings/full-gradient-heading/metadata.json
- contents/typography/headings/metadata.json
- contents/typography/headings/partial-gradient/index.tsx
- contents/typography/headings/partial-gradient/metadata.json
Closes #144 
This PR adds full and partial gradient example for `Headings`.
No
> Added full and partial gradient `Heading` component examples

- contents/data-display/tags/card-with-tags/index.tsx
- contents/data-display/tags/card-with-tags/metadata.json
- contents/data-display/tags/metadata.json
- contents/data-display/tags/reorder-tags/index.tsx
- contents/data-display/tags/reorder-tags/metadata.json
Closes #145 
This PR adds `Tags` component examples.
No
> Added `Tags` component examples

- contents/layouts/dividers/label-on-left/index.tsx
- contents/layouts/dividers/label-on-left/metadata.json
- contents/layouts/dividers/metadata.json
- contents/layouts/dividers/with-button/index.tsx
- contents/layouts/dividers/with-button/metadata.json
- contents/layouts/dividers/with-icon/index.tsx
- contents/layouts/dividers/with-icon/metadata.json
- contents/layouts/dividers/with-label/index.tsx
- contents/layouts/dividers/with-label/metadata.json
- contents/layouts/dividers/with-title-and-button/index.tsx
- contents/layouts/dividers/with-title-and-button/metadata.json
- contents/layouts/dividers/with-title-on-left/index.tsx
- contents/layouts/dividers/with-title-on-left/metadata.json
- contents/layouts/dividers/with-title/index.tsx
- contents/layouts/dividers/with-title/metadata.json
- contents/layouts/dividers/with-toolbar/index.tsx
- contents/layouts/dividers/with-toolbar/metadata.json
Closes #143
This PR adds `Divider` component examples.
No
> Added `Divider` component examples

- scripts/observe-pull-requests.ts
- Uncomment and update pull request logic.
- Increased reviewer count from 2 to 4.
No
> Uncomment and update pull request logic

- contents/data-display/dnd/list/index.tsx
- contents/data-display/dnd/list/metadata.json
- contents/data-display/dnd/metadata.json
- contents/data-display/dnd/with-handle/index.tsx
- contents/data-display/dnd/with-handle/metadata.json
Closes #81 
This PR adds `Drag'n'Drop` component examples.
No
> Added `Drag'n'Drop` components

- components/data-display/code-block.tsx
Closes #205 
Simplified rendering logic.
No
> Simplified rendering logic

- plop/component/metadata.json.hbs
> fix: remove unnecessary options

- components/overlay/mobile-menu.tsx
Closes #225
This PR automatically hides scrollbar if unnecessary.
Scrollbar is always shown.
Scrollbar hides if unncessary.
No
> fix: fixed overflowY scrollbar to be auto

- theme/semantics.ts
Closes #228 
Updated color values for muted colors.
No
> Updated color values for muted colors

- contents/disclosure/metadata.json
- contents/disclosure/tabs/metadata.json
- contents/disclosure/tabs/with-badges/index.tsx
- contents/disclosure/tabs/with-badges/metadata.json
- contents/disclosure/tabs/with-full-width/index.tsx
- contents/disclosure/tabs/with-full-width/metadata.json
- contents/disclosure/tabs/with-icons/index.tsx
- contents/disclosure/tabs/with-icons/metadata.json
- pages/disclosure/[[...slug]].page.tsx
Closes #191  
Aadded tabs component examples.
> Aadded tabs component examples

- i18n/ui.en.json
Closes #222
This fixes the search result title.
{labels} of components
{labels} components
No
> fix(search): fixed english for search result title in `ui.en.json`

- scripts/observe-pull-requests.ts
Related yamada-ui/yamada-ui#2099
Added additional Discord role mention in alert.
No
> Added additional Discord role mention in alert

- contents/forms/dropzones/with-button/index.tsx
- contents/forms/dropzones/with-button/metadata.json
Closes #210
This fixes the color being white regardless of the current theme mode. Also fixed the position of select files button.
White font color even if light mode.
Change to black font in light mode.
No
> fix(dropzones): fixed the font color of title and position of button

- .github/workflows/observe-issue-and-pull-request.yml
- .github/workflows/reviewer-pull-request.yml
- package.json
- scripts/observe-issues.ts
- scripts/observe-pull-requests.ts
- scripts/reviewer-pull-requests.ts
- scripts/utils.ts
Related yamada-ui/yamada-ui#2100
Add and update GitHub Actions workflows.
No
> Add and update GitHub Actions workflows

- contents/data-display/comments/comment/index.tsx
- contents/data-display/comments/with-html-content/index.tsx
Closes #209
This PR makes the `comments` example more responsive.
It did not look great on smaller screens.
By using grid, the comments look better on smaller screen.
No
> fix(comments): made the `comments` examples be more responsive

- contents/layouts/grids/leading-item/index.tsx
Closes #212
This PR fixes the responsiveness of `Grid with leading items`.
No
> fix(grids): improved the gridTemplateAreas for `grid` component example

- contents/feedback/progress/metadata.json
- contents/feedback/skeleton/metadata.json
- contents/navigation/navbars/metadata.json
- contents/navigation/paginations/metadata.json
- contents/navigation/steppers/metadata.json
- contents/overlay/context-menus/metadata.json
- contents/overlay/dialogs/metadata.json
- contents/overlay/drawers/metadata.json
- contents/overlay/menus/metadata.json
- contents/typography/texts/metadata.json
Closes #220
I have created temporary directories for categories we need for releasing Yamada Components.
No
The titles and descriptions inside `metadata.json` are AI-generated, so it may be inaccurate. We can fix this in another PR when we create the examples.
> feat(directories): added directories for categories that are required for release

- contents/navigation/navbars/simple-navbar/index.tsx
- contents/navigation/navbars/simple-navbar/metadata.json
> feat: add SimpleNavbar

- contents/forms/buttons/primary-button/index.tsx
- contents/forms/buttons/primary-button/metadata.json
- package.json
Related #75 
add Primary Buttons
> feat: button-component

- contents/data-display/banners/cookie/index.tsx
- contents/data-display/banners/cookie/metadata.json
- contents/data-display/banners/metadata.json
- pnpm-lock.yaml
Closes #89 
add `banners` component
No
None
> feat: add `banners` component

- contents/navigation/metadata.json
- contents/navigation/paginations/centered-full-width/index.tsx
- contents/navigation/paginations/centered-full-width/metadata.json
- contents/navigation/paginations/right-justified-with-page-position/index.tsx
- contents/navigation/paginations/right-justified-with-page-position/metadata.json
- contents/navigation/paginations/simple-button/index.tsx
- contents/navigation/paginations/simple-button/metadata.json
Closes #190 
This PR adds examples of Paginations.
> Added Paginations component examples

- @types/search.d.ts
- pages/search/index.page.tsx
- scripts/search-content.ts
- utils/i18n.ts
Added typings and enhanced query resolution.
No
> Added typings and enhanced query resolution

- contents/layouts/footers/footer-centerd/index.tsx
- contents/layouts/footers/footer-centerd/metadata.json
- contents/layouts/footers/footer-links/index.tsx
- contents/layouts/footers/footer-simple/index.tsx
- contents/layouts/footers/footer-social-icons/index.tsx
Closes #211
This PR fixes styles of the footer component examples.
Did not have max width.
Adds max-width to footer and make it `as="footer"`.
No
> fix(footers): fixed styles of footer component examples

- contents/feedback/alerts/with-accent-border/index.tsx
- contents/feedback/alerts/with-accent-border/metadata.json
- contents/feedback/alerts/with-actions/index.tsx
- contents/feedback/alerts/with-actions/metadata.json
- contents/feedback/alerts/with-description/index.tsx
- contents/feedback/alerts/with-description/metadata.json
- contents/feedback/alerts/with-dismiss-button/index.tsx
- contents/feedback/alerts/with-dismiss-button/metadata.json
- contents/feedback/alerts/with-link-on-right/index.tsx
- contents/feedback/alerts/with-link-on-right/metadata.json
- contents/feedback/alerts/with-list/index.tsx
- contents/feedback/alerts/with-list/metadata.json
Closes #219
This fixes the typo and styles of `Alerts` component examples.
No
> refactor(alerts): fix typo and styles of `alerts` examples

- contents/layouts/headers/with-tabs/index.tsx
- contents/layouts/headers/with-tabs/metadata.json
Closes #260
This adds a `Header` component example with tabs.
No
> feat(headers): added `header` with tabs

- contents/data-display/metadata.json
- contents/data-display/stats/metadata.json
- contents/data-display/tags/metadata.json
- contents/disclosure/metadata.json
- contents/disclosure/tabs/metadata.json
- contents/feedback/alerts/metadata.json
- contents/feedback/metadata.json
- contents/feedback/progress/metadata.json
- contents/feedback/skeleton/metadata.json
- contents/forms/button-group/metadata.json
- contents/forms/buttons/metadata.json
- contents/forms/dropzones/metadata.json
- contents/forms/inputs/metadata.json
- contents/forms/metadata.json
- contents/layouts/dividers/metadata.json
- contents/layouts/grids/metadata.json
- contents/layouts/metadata.json
- contents/navigation/metadata.json
- contents/navigation/paginations/metadata.json
- contents/overlay/context-menus/metadata.json
- contents/overlay/dialogs/metadata.json
- contents/overlay/drawers/metadata.json
- contents/overlay/menus/metadata.json
- contents/overlay/metadata.json
- contents/typography/headings/full-gradient-heading/metadata.json
- contents/typography/headings/metadata.json
- contents/typography/headings/partial-gradient/metadata.json
- contents/typography/metadata.json
- contents/typography/texts/metadata.json
Closes #269
I have replaced the title and description to match yamada ui docs.
No
> refactor(metadata): replaced title and description to match yamada ui docs

- contents/navigation/navbars/double-navbar/index.tsx
- contents/navigation/navbars/double-navbar/metadata.json
> feat: add `double-navbar`

- contents/navigation/navbars/navbar-with-segmentedcontrol/index.tsx
- contents/navigation/navbars/navbar-with-tooltips/index.tsx
- contents/navigation/navbars/simple-navbar/index.tsx
> fix: fix Icon import

- components/data-display/component-card.tsx
Closes #285
I have modified the icon imports to use `{IconName}Icon`.
No
> fix(component-card): fixed icon imports in `component-card`

- components/data-display/component-code-preview.tsx
Closes #286
I have modified the icon imports to use `{IconName}Icon`.
No
> refactor(component-code-preview): update lucide icon import

- components/forms/copy-button.tsx
Closes #288
I have modified the icon imports to use `{IconName}Icon`.
No
> refactor(copy-button): update `lucide icon` imports

- contents/page-sections/authentication/authentication-form/index.tsx
- contents/page-sections/authentication/authentication-form/twitter-button.tsx
Closes #302 
Append Icon to the end of the name of the Icon being imported
> fix(authentication): rename IconName to {IconName}Icon

- components/forms/color-mode-button.tsx
Closes #287
I have modified the icon imports to use `{IconName}Icon`.
No
> refactor(color-mode-button): update `lucide icon` import

- contents/navigation/navbars/navbar-with-tooltips/metadata.json
- contents/navigation/navbars/simple-navbar/metadata.json
> fix: formatted

- contents/forms/buttons/primary-button/metadata.json
fix format for PrimaryButton in contents/forms/buttons/primary-button/metadata.json
Closes # Github issue #323
> fix: format for PrimaryButton

- contents/page-sections/authentication/forgot-password/index.tsx
- contents/page-sections/authentication/with-image/index.tsx
- contents/page-sections/authentication/with-title/index.tsx
Closes #  Github issue #324 
Fix icon imports in authetication
> Fix icon imports in authentication

- contents/feedback/progress/quest-progress/index.tsx
- contents/feedback/progress/quest-progress/metadata.json
> feat: add `QuestProgress`

- @types/component.d.ts
- components/data-display/component-card.tsx
- components/data-display/component-preview.tsx
- components/layouts/component-body.tsx
- contents/overlay/drawers/with-close-button-on-outside/index.tsx
- contents/overlay/drawers/with-close-button-on-outside/metadata.json
- layouts/component-layout.tsx
- package.json
- pnpm-lock.yaml
Closes #309 
Toggle use of iframe.
Added display in iframe when iframe is specified as true in metadata.json
> Feat Toggle use of iframe

- contents/page-sections/metadata.json
> fix: `page-sections` metadata missing description

- components/forms/search.tsx
> fix: fixed #289

- contents/overlay/menus/menu-with-icon/index.tsx
- contents/overlay/menus/simple-menu/index.tsx
- contents/overlay/menus/simple-with-descriptions/index.tsx
Closes  Github issue #301 
Fix icon imports in menus
> Fix icon imports in menus

- contents/layouts/footers/footer-centerd/index.tsx
- contents/layouts/footers/footer-links/index.tsx
- contents/layouts/footers/footer-social-icons/index.tsx
> fix the imports in layouts/footers

- contents/layouts/dividers/with-button/index.tsx
- contents/layouts/dividers/with-title-and-button/index.tsx
- contents/layouts/dividers/with-toolbar/index.tsx
> fix imports in layouts/dividers

- components/navigation/tree.tsx
> fix imports in components/navigation/tree.tsx

- components/layouts/header.tsx
> fix imports in components/layouts/header.tsx

- components/forms/theme-scheme-button.tsx
> fix imports in forms/theme-scheme-button.tsx

- contents/data-display/dnd/with-handle/index.tsx
- contents/disclosure/tabs/with-icons/index.tsx
- contents/forms/buttons/copy-button/index.tsx
- contents/forms/dropzones/with-button/index.tsx
Closes Github issue #294 #295 #296 #297
> fix imports in contents

- contents/data-display/banners/metadata.json
> fix: `banners` metadata missing translations 

- contents/overlay/context-menus/mail-box/index.tsx
- contents/overlay/context-menus/mail-box/mail-item.tsx
- contents/overlay/context-menus/mail-box/metadata.json
> feat: add mailbox

- .github/composite-actions/install/action.yml
Updated pnpm action to v3.0.0.
See https://github.com/yamada-ui/yamada-components/actions/runs/9818211229/job/27126985870
No
> Updated pnpm action to v3.0.0

- components/data-display/component-preview.tsx
> fix: remove `UIProvider` and rename `CustomUIProvider`

- contents/overlay/dialogs/cookie-dialog/index.tsx
- contents/overlay/dialogs/cookie-dialog/metadata.json
Related #152
Added example of cookie dialog.
No.
I will add examples other than cookies as soon as I create them.
> Added `Dialogs` example

- contents/feedback/skeletons/profile-skeleton/index.tsx
- contents/feedback/skeletons/profile-skeleton/metadata.json
Closes #353
I have refactored the `Skeleton` example.
No
> refactor(skeleton): improved `skeleton` component example

- scripts/contributors.ts
Closes #355
I have fixed few issues in the `contributors` script.
No
> refactor(script): fixed issues in `contributors` script

- contents/overlay/dialogs/cookie-dialog/index.tsx
- contents/overlay/dialogs/cookie-dialog/metadata.json
- contents/overlay/dialogs/input-dialog/index.tsx
- contents/overlay/dialogs/input-dialog/metadata.json
- contents/overlay/dialogs/simple-dialog/index.tsx
- contents/overlay/dialogs/simple-dialog/metadata.json
Related #152
Added examples of simple dialog and input dialog.
No.
> Added `Dialog` examples

- .github/workflows/observe-issue-and-pull-request.yml
Updated json formatting in script.
No
> Updated json formatting in script

- components/data-display/component-preview.tsx
Closes #349 
When using iframe, the whole theme is not reflected, so implement this and fix it.
> feat: add `EnvironmentProvider`

- contents/overlay/dialogs/gdpr-cookie-dialog/category-item.tsx
- contents/overlay/dialogs/gdpr-cookie-dialog/data.ts
- contents/overlay/dialogs/gdpr-cookie-dialog/index.tsx
- contents/overlay/dialogs/gdpr-cookie-dialog/metadata.json
- contents/overlay/dialogs/gdpr-cookie-dialog/table.tsx
Closes #152
Added GDPR Cookie to `Dialog` example
No.
> Added GDPR Cookie to `Dialog` example

- contents/navigation/steppers/simple-stepper/index.tsx
- contents/navigation/steppers/simple-stepper/metadata.json
- contents/navigation/steppers/simple-stepper/ripple-step.tsx
> feat: add `SimpleStepper`

- .github/workflows/sync.yml
Updated token in GitHub Actions workflow.
No
> Updated token in GitHub Actions workflow

- components/data-display/component-preview.tsx
> fix: add `overflow: auto;`

- contents/overlay/dialogs/cookie-dialog/metadata.json
- contents/overlay/dialogs/gdpr-cookie-dialog/metadata.json
- contents/overlay/dialogs/input-dialog/metadata.json
- contents/overlay/dialogs/three-buttons-dialog/index.tsx
- contents/overlay/dialogs/three-buttons-dialog/metadata.json
Related #152
I have added a new dialog example.
> Added `Dialog` example

- contents/page-sections/authentication/with-image/index.tsx
> fix: add backgroudImage height and Center position

- @types/component.d.ts
- contents/navigation/steppers/simple-stepper/metadata.json
- contents/overlay/dialogs/gdpr-cookie-dialog/metadata.json
- utils/component.ts
> feat: implemented file reordering process

- contents/layouts/headers/double-header/index.tsx
- contents/layouts/headers/simple-header/index.tsx
> fix: remove container query

- .github/composite-actions/install/action.yml
- .github/workflows/sync.yml
Updated GitHub Actions to latest versions.
No
> Updated GitHub Actions to latest versions

- package.json
Updated node version and pnpm.
No
> Updated node version and pnpm

- contents/overlay/drawers/form-drawer/index.tsx
- contents/overlay/drawers/form-drawer/metadata.json
Related #278
New `Drawer` example added.
No.
> Add `Drawer` example

- .github/composite-actions/install/action.yml
Updated pnpm action setup in CI config.
No
> Updated pnpm action setup in CI config

- .github/workflows/observe-issue-and-pull-request.yml
Updated payload structure in workflow.
No
> Updated payload structure in workflow

- .github/workflows/observe-issue-and-pull-request.yml
Updated curl payload in GitHub workflow.
No
> Updated curl payload in GitHub workflow

- utils/component.ts
> Component preview is not working properly

- contents/layouts/grids/asymmetrical-columns/index.tsx
- contents/layouts/grids/leading-item/index.tsx
> refactor: breakpoints-layouts-grids

- contents/layouts/footers/footer-centerd/index.tsx
- contents/layouts/footers/footer-links/index.tsx
- contents/layouts/footers/footer-simple/index.tsx
- contents/layouts/footers/footer-social-icons/index.tsx
Closes #401 #315
I have updated the footer to have better spacing and sizes, and replaced `_container`.
No
> refactor(footer): update footer layouts

- components/data-display/component-preview.tsx
Closes #407  
`size` has been deprecated and has been modified.
> fix: changed `size` to `boxSize`

- @types/component.d.ts
- contents/navigation/steppers/simple-stepper/metadata.json
- contents/overlay/dialogs/gdpr-cookie-dialog/metadata.json
- utils/component.ts
Closes #422
I have changed `fileList` to be 
```json
"files": {
"order": ["index.tsx"]
}
```
No
> refactor(tab-order): changed `fileList` to be `files.order`

- components/data-display/component-preview.tsx
- components/layouts/component-body.tsx
Closes #395
Update ComponentPreview props and layout.
No
> Update ComponentPreview props and layout

- contents/data-display/avatars/avatar-with-text/index.tsx
- contents/data-display/avatars/avatars-with-hover-motion/index.tsx
- contents/data-display/avatars/avatars-with-hover-motion/metadata.json
- contents/data-display/avatars/avatars-with-hover-motion/users.ts
- contents/data-display/avatars/avatars-with-hover/index.tsx
- contents/data-display/avatars/avatars-with-hover/metadata.json
- contents/data-display/avatars/avatars-with-hover/users.ts
Closes #403
I have added animated avatar examples.
No
> feat(avatar): added animated `avatar` examples

- contents/page-sections/faq/with-image/index.tsx
> refactor: breakpoints-page-sections/faq

- lefthook.yaml
Update lefthook config for prettier and eslint.
No
> Update lefthook config for prettier and eslint

- .github/workflows/sync.yml
> Updated commit message

- contents/overlay/drawers/form-drawer/index.tsx
- contents/overlay/drawers/navigation-drawer/data.ts
- contents/overlay/drawers/navigation-drawer/index.tsx
Closes #425
I have refactored the `drawer` component examples.
No
> refactor(drawer): improved drawer visual design and code

- contents/page-sections/contact-us/form/contacts.ts
- contents/page-sections/contact-us/form/index.tsx
- contents/page-sections/contact-us/form/metadata.json
- contents/page-sections/contact-us/metadata.json
- contents/page-sections/contact-us/touch-form/contacts.ts
- contents/page-sections/contact-us/touch-form/index.tsx
- contents/page-sections/contact-us/touch-form/metadata.json
Closes #87
I have added `contact us` page section examples.
No
> feat(contact-us): added `contact us` page section examples

- contents/data-display/charts/weekly-temperature-chart/index.tsx
- contents/data-display/charts/weekly-temperature-chart/locations.ts
- contents/data-display/charts/weekly-temperature-chart/metadata.json
- contents/data-display/charts/weekly-temperature-chart/utils.ts
Closes #427
I have added a better range picker for the date and refactored the style.
No
> refactor(chart): improved `chart` range selector and style

- contents/data-display/charts/simple-charts/index.tsx
- contents/data-display/charts/simple-charts/metadata.json
Added simple charts example.
NIL
NIL
No
> added simple charts

- contents/data-display/charts/bar-chart-label/index.tsx
- contents/data-display/charts/bar-chart-label/metadata.json
Added `BarChart` with label example.
NIL
NIL
No
> added `BarChart` with  label example

- contents/navigation/steppers/simple-stepper/metadata.json
- contents/overlay/dialogs/gdpr-cookie-dialog/metadata.json
- utils/component.ts
Closes #429
I have made the files order to prioritise `index.tsx` unless specified. Also, I have made it so `.tsx` files will go before `.ts` in the order unless specified.
No
> refactor(metadata): improved files order logic

- components/data-display/component-code-preview.tsx
- components/layouts/component-body.tsx
> Fix code preview border top

- .github/workflows/sync.yml
Updated token in sync workflow.
No
> Updated token in sync workflow

- utils/array.ts
Updated MixedArray type definition.
No
> Updated MixedArray type definition

- contents/data-display/charts/temperature-chart/index.tsx
- contents/data-display/charts/temperature-chart/utils.ts
Related #441
Refactored the data acquisition process for the temperature chart.
NIL
NIL
No
> refactor of temperature chart

- contents/data-display/charts/chart-with-text/index.tsx
- contents/data-display/charts/chart-with-text/metadata.json
- contents/layouts/headers/double-header/index.tsx
- contents/layouts/headers/with-tabs/index.tsx
- package.json
- pnpm-lock.yaml
Closes #438
Added example of displaying text in the center of charts.
NIL
NIL
No
> feat: added Chart with Text example

- theme/tokens/fonts.ts
- theme/tokens/index.ts
Added font tokens for styling.
Currently, downloading `inter` but did not use it in the application.
No
> Added font tokens for styling

- contents/overlay/dynamic-islands/dynamic-island/index.tsx
- contents/overlay/dynamic-islands/dynamic-island/metadata.json
- contents/overlay/dynamic-islands/metadata.json
- contents/overlay/dynamic-islands/music-dynamic-island/index.tsx
- contents/overlay/dynamic-islands/music-dynamic-island/metadata.json
- contents/overlay/dynamic-islands/phone-call-dynamic-island/index.tsx
- contents/overlay/dynamic-islands/phone-call-dynamic-island/metadata.json
- contents/overlay/dynamic-islands/simple-dynamic-island/index.tsx
- contents/overlay/dynamic-islands/simple-dynamic-island/metadata.json
- contents/overlay/dynamic-islands/springy-dynamic-island/index.tsx
- contents/overlay/dynamic-islands/springy-dynamic-island/metadata.json
Closes #456
I have added `Dynamic Island` component examples.
No
I am still unsure about which category group to place this in.
> feat(dynamic-islands): added `dynamic-island` component examples

- contents/data-display/comments/comment/index.tsx
- contents/data-display/comments/with-html-content/index.tsx
Closes #471
Refactored `Comment` component examples.
No
> refactor(comments): updated `comments` styles

- contents/page-sections/hero-headers/with-background-image/index.tsx
- contents/page-sections/hero-headers/with-bullets/index.tsx
- contents/page-sections/hero-headers/with-content-on-left/index.tsx
Closes #466
Refactored `Hero` component examples.
No
> refactor(hero): updated `hero` styles

- contents/typography/texts/on-scroll/index.tsx
Closes #464
Refactored `Text` component examples.
No
> refactor(texts): updated `texts` styles

- contents/data-display/timeline/animated-timeline/calendar-icon.tsx
- contents/data-display/timeline/animated-timeline/index.tsx
- contents/data-display/timeline/animated-timeline/metadata.json
- contents/data-display/timeline/animated-timeline/timeline-item.tsx
- contents/data-display/timeline/animated-timeline/timeline.ts
- contents/data-display/timeline/animated-timeline/utils.ts
- contents/data-display/timeline/custom-icon/calendar-icon.tsx
- contents/data-display/timeline/custom-icon/index.tsx
- contents/data-display/timeline/custom-icon/metadata.json
- contents/data-display/timeline/custom-icon/timeline-item.tsx
- contents/data-display/timeline/custom-icon/timeline.ts
- contents/data-display/timeline/metadata.json
- contents/data-display/timeline/middle-line/calendar-icon.tsx
- contents/data-display/timeline/middle-line/index.tsx
- contents/data-display/timeline/middle-line/metadata.json
- contents/data-display/timeline/middle-line/timeline-item.tsx
- contents/data-display/timeline/middle-line/timeline.ts
- contents/data-display/timeline/middle-line/utils.ts
- contents/data-display/timeline/simple-timeline/index.tsx
- contents/data-display/timeline/simple-timeline/metadata.json
- contents/data-display/timeline/simple-timeline/timeline-item.tsx
- contents/data-display/timeline/simple-timeline/timeline.ts
Closes #450
I have added a way to implement timeline component without waiting for it to release.
No
This may be removed once someone makes the `Timeline` component in Yamada UI.
> feat(timeline): added `timeline` component examples

- contents/layouts/footers/footer-centered/index.tsx
- contents/layouts/footers/footer-links/index.tsx
- contents/layouts/footers/footer-simple/index.tsx
Closes #463
Refactored `Footer` component examples.
No
> refactor(footers): updated `footer` styles

- contents/overlay/dialogs/cookie-dialog/index.tsx
- contents/overlay/dialogs/gdpr-cookie-dialog/category-item.tsx
- contents/overlay/dialogs/gdpr-cookie-dialog/data.ts
- contents/overlay/dialogs/gdpr-cookie-dialog/index.tsx
- contents/overlay/dialogs/gdpr-cookie-dialog/metadata.json
- contents/overlay/dialogs/input-dialog/index.tsx
- contents/overlay/dialogs/simple-dialog/index.tsx
- contents/overlay/dialogs/three-buttons-dialog/index.tsx
Closes #460
Refactored `dialog` component examples.
Solved some styling issues.
No.
> refactor(dialogs): updated `dialog` styles

- contents/data-display/avatars/avatar-with-text/index.tsx
- contents/data-display/avatars/avatars-with-hover-motion/index.tsx
- contents/data-display/avatars/avatars-with-hover/index.tsx
Closes #466
Refactored `Avatar` component examples.
No
> refactor(avatars): updated `avatars` styles

- contents/forms/dropzones/with-button/index.tsx
- contents/forms/dropzones/with-image-preview/index.tsx
Closes #465
Refactored `Dropzone` component examples.
No
> refactor(dropzones): updated `dropzone` styles

- contents/data-display/charts/bar-chart-label/index.tsx
> Specify maxW for barchart

- contents/navigation/navbars/double-navbar/index.tsx
- contents/navigation/navbars/navbar-with-tooltips/index.tsx
- contents/navigation/navbars/simple-navbar/index.tsx
- contents/navigation/navbars/with-segmented-control/index.tsx
Closes #495  
- Reduced font size
- Correction of avatar size
- Color correction of borderRight
- Change Badge to Tag
> Refactor `Navbar` component examples 

- contents/feedback/progress/quest-progress/index.tsx
- contents/navigation/navbars/double-navbar/index.tsx
- contents/overlay/menus/menu-with-icon/index.tsx
Closes # 
```<CircleCheckBigIcon size="6xl" />```
```diff
- <CircleCheckBigIcon size="6xl" />
+ <CircleCheckBigIcon fontSize="6xl" />
```
**No**
> fix(fontSize): modified icon size to fontSize

- contents/typography/texts/on-scroll/index.tsx
> fix: change fontWeight in `Text`

- contents/layouts/headers/metadata.json
- contents/layouts/headers/with-search/index.tsx
- contents/layouts/headers/with-search/metadata.json
Closes #490
Added header with search box in headers category.
No.
> Added header with search box

- contents/feedback/progress/quest-progress/index.tsx
Closes #505
Fixes the visual issues in the Quest Progress component:
- Reduced the excessive white space around the progress bar.
- Added rounded corners to the progress bar to make it consistent with the overall design.
- The current progress bar has too much white space around it.
- The corners of the progress bar are not rounded.
- The progress bar now has reduced white space, making it more aligned with the design.
- Rounded corners have been added to the progress bar, making it uniform with other UI components.
No
None
> fix(progress-bar): reduce whitespace and add rounded corners in Quest Progress Component

- contents/data-display/banners/announcement/index.tsx
- contents/data-display/banners/announcement/metadata.json
- contents/data-display/banners/cookie/index.tsx
> Refactor `data-display/banners/cookie`

- i18n/content.en.json
- i18n/content.ja.json
- scripts/search-content.ts
> fix: add `ignore` process in `search-content.ts`

- contents/forms/inputs/confirmation-with-overlay/index.tsx
- contents/forms/inputs/confirmation-with-overlay/indicator.tsx
- contents/forms/inputs/confirmation-with-overlay/metadata.json
- contents/forms/inputs/confirmation-with-overlay/overlay.tsx
- contents/forms/inputs/metadata.json
Closes #482
I have added a password confirmation input example with an overlay.
No
> feat(input): added `input` with overlay

- contents/layouts/headers/with-tabs/index.tsx
Closes #489 
"Remove 'blackAlpha' background in header Flex component for black/white mode"
The background color is slightly gray.
The background color goes back to normal.
No
Nada
> chore: remove background color prop from header Flex component

- contents/page-sections/faq/page-header/contacts.ts
- contents/page-sections/faq/page-header/index.tsx
- contents/page-sections/faq/page-header/links.ts
- contents/page-sections/faq/page-header/metadata.json
Closes #529
I have added a FAQ page with page header
N/A
N/A
No
N/A
> feat(faq): added faq page with page header

- contents/navigation/navbars/navbar-nested/index.tsx
- contents/navigation/navbars/navbar-nested/label.tsx
- contents/navigation/navbars/navbar-nested/links.ts
- contents/navigation/navbars/navbar-nested/metadata.json
- contents/navigation/navbars/navbar-nested/nested.tsx
- contents/navigation/navbars/navbar-nested/types.ts
- contents/navigation/navbars/navbar-nested/user-menu.tsx
Closes #528
I have added a new navbar with nested links component example.
N/A
New component in navbars.
No
N/A
> Added `navbar` with nested link component example

- contents/layouts/headers/with-search/index.tsx
Fixed `header component with search box` styles.
Made some style changes that were pointed out in a previous meeting.
> Fixed  `header component with search box`
